version: '3'
services:
  mongo:
    image: mongo:4.0.0
    ports:
      - 27017:27017
    volumes:
      - ./dc-files/mongo:/docker-entrypoint-initdb.d
#    environment:
#      MONGO_INITDB_DATABASE: erp
  redis:
    image: redis
    ports:
      - 6379:6379
  test:
    image: node:12.10.0
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "yarn && NODE_ENV=docker_local yarn test"
